### ISSUE TITLE
Script does not work with hubic

### ISSUE THREAD

**Issue by forty** [GilGalaad/duplicity-rclone#3]
Hi,
I am trying to use your script with hubic (OVH cloud storage), I think it almost work, the only issue I have is that I normally access the bucket like this
> rclone ls hubic:default/backup/

and this does not work:
> rclone ls hubic:/default/backup/

consequently, I need to do that on duplicity:
> duplicity  list-current-files rclone://hubic:default/backup/

which breaks because duplicity thinks that the bucket name (default) is the port number...

My workaround is to change the script like this:
```
if parsed_url.path.startswith('//'):
                    self.remote_path = self.remote_path[2:].replace('/',':',1)
```

which allows me do do this:
> duplicity  list-current-files rclone://hubic/default/backup/

and the first / is understood as :

**Comment by GilGalaad** [comment]
Fix implemented (almost) as you suggested, and readme updated accordingly.
Actually, it was entirely my fault, because almost every storage provider wants the first bucket/directory without trailing slash, but some (the ones I tested) work in both ways. So it's more correct to have always a trailing slash in command line, and remove it always in the backend.
Now it works with Hubic and with Google Drive as well.
Thank you for your help!

```
Command line: duplicity /store/audio/classical rclone://hubic:/default/backup/classical
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: none
Last full backup is too old, forcing full backup
--------------[ Backup Statistics ]--------------
StartTime 1503405084.48 (Tue Aug 22 14:31:24 2017)
EndTime 1503405547.20 (Tue Aug 22 14:39:07 2017)
ElapsedTime 462.72 (7 minutes 42.72 seconds)
SourceFiles 86
SourceFileSize 596753449 (569 MB)
NewFiles 86
NewFileSize 596753449 (569 MB)
DeletedFiles 0
ChangedFiles 0
ChangedFileSize 0 (0 bytes)
ChangedDeltaSize 0 (0 bytes)
DeltaEntries 86
RawDeltaSize 596753362 (569 MB)
TotalDestinationSizeChange 581931618 (555 MB)
Errors 0
-------------------------------------------------
```
